name: Integrating docker via Github Actions
on:
  # 'branches' is invalid under 'workflow_dispatch'. It must stand alone.
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Cloning Github Repository
        # v7.0.0 does not exist. v4 is the current standard.
        uses: actions/checkout@v4

      - name: Setup Username and Password for Docker
        uses: docker/login-action@v3
        with:
          username: shashankj017 
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build an image from Dockerfile
        run: docker build -t ${{ vars.DOCKER_IMAGE }} .

      - name: Tag the Image
        run: docker tag ${{ vars.DOCKER_IMAGE }} ${{ vars.DOCKER_USERNAME }}/${{ vars.DOCKER_IMAGE }}:v1

      - name: Push the image to Dockerhub
        run: docker push ${{ vars.DOCKER_USERNAME }}/${{ vars.DOCKER_IMAGE }}:v1
